name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  d_button: ^0.0.10
  d_info: ^0.2.0
  d_input: ^0.5.1
  d_method: ^0.2.6
  d_view: ^0.0.5
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  intl: ^0.20.2
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
