name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  d_button: ^0.0.10
  d_info: ^0.2.0
  d_input: ^0.5.1
  d_method: ^0.2.6
  d_view: ^0.0.5
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  grouped_list: ^6.0.0
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1
  whatsapp_unilink: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
